version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  api:
    image: droid-pecas
    env_file:
      - .env
    build: .
    # command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  
volumes:
  postgres_data_dev:
    driver: local